import { Product } from './types';

// Raw data source
const RAW_DATA = [
  // Hair Care
  { id: 1, name: "Head & Shoulders 2in1 Anti Dandruff", size: "1 L", price: 999, category: "Hair Care", brand: "Head & Shoulders", desc: "Anti-dandruff shampoo and conditioner." },
  { id: 2, name: "Head & Shoulders Anti Dandruff (Cool)", size: "1 L", price: 999, category: "Hair Care", brand: "Head & Shoulders", desc: "Cool sensation shampoo." },
  { id: 3, name: "Vatika Naturals Ayurvedic Shampoo", size: "1 L", price: 699, category: "Hair Care", brand: "Vatika", desc: "Natural herbal ingredients." },
  { id: 5, name: "Vatika Smoothing Keratin Shampoo", size: "200 ML", price: 475, category: "Hair Care", brand: "Vatika", desc: "Smoothens and straightens hair." },
  { id: 6, name: "Pantene Pro-V Shampoo", size: "650 ML", price: 645, category: "Hair Care", brand: "Pantene", desc: "Strengthens hair roots." },
  { id: 7, name: "Simco Extra Care Herbal Shampoo", size: "1 L", price: 399, category: "Hair Care", brand: "Simco", desc: "Herbal shampoo." },
  { id: 8, name: "Herbal Essences Shampoo", size: "400 ML", price: 700, category: "Hair Care", brand: "Herbal Essences", desc: "With natural extracts." },
  { id: 9, name: "Denver Onion Shampoo", size: "300 ML", price: 349, category: "Hair Care", brand: "Denver", desc: "Prevents hair fall." },
  { id: 10, name: "TruthSome Anti-Frizz Shampoo", size: "300 ML", price: 599, category: "Hair Care", brand: "TruthSome", desc: "Controls frizzy hair." },
  { id: 11, name: "Nyle Naturals Anti Hairfall", size: "400 ML", price: 225, category: "Hair Care", brand: "Nyle", desc: "Hair fall reduction shampoo." },
  { id: 15, name: "Parachute Ayurvedic Cooling Oil", size: "200 ML", price: 275, category: "Hair Care", brand: "Parachute", desc: "Cooling hair oil." },
  { id: 16, name: "Head & Shoulders Shampoo", size: "180 ML", price: 215, category: "Hair Care", brand: "Head & Shoulders", desc: "Anti-dandruff shampoo." },
  { id: 26, name: "Alphavedic AntiFrizz Shampoo", size: "100 ML", price: 595, category: "Hair Care", brand: "Alphavedic", desc: "Removes dryness." },
  { id: 27, name: "Good Vibes Castor Oil", size: "200 ML", price: 285, category: "Hair Care", brand: "Good Vibes", desc: "Thickens hair." },
  { id: 35, name: "Park Avenue Beer Shampoo", size: "70 ML", price: 40, category: "Hair Care", brand: "Park Avenue", desc: "Adds shine to hair." },
  { id: 53, name: "Navratna Ayurvedic Oil", size: "100 ML", price: 100, category: "Hair Care", brand: "Navratna", desc: "Cooling oil." },
  { id: 59, name: "Phy Shampoo", size: "200 ML", price: 450, category: "Hair Care", brand: "Phy", desc: "Shampoo for men." },
  { id: 64, name: "Dove Dry Shampoo", size: "141 g", price: 625, category: "Hair Care", brand: "Dove", desc: "Waterless hair cleaning spray." },
  { id: 88, name: "Clarsta Rosemary Shampoo", size: "250 ml", price: 349, category: "Hair Care", brand: "Clarsta", desc: "With rosemary extracts." },
  { id: 94, name: "Bajaj Henna", size: "75 g", price: 35, category: "Hair Care", brand: "Bajaj", desc: "Natural henna." },
  { id: 104, name: "Winyfred Anti Hairfall", size: "250 ml", price: 749, category: "Hair Care", brand: "Winyfred", desc: "Prevents hair fall." },
  { id: 105, name: "Winyfred Keratin Smooth", size: "250 ml", price: 749, category: "Hair Care", brand: "Winyfred", desc: "Keratin shampoo." },
  { id: 106, name: "Mamaearth Volume Shampoo", size: "300 ml", price: 1599, category: "Hair Care", brand: "Mamaearth", desc: "Volume boosting shampoo." },
  { id: 107, name: "Mamaearth Damage Shampoo", size: "300 ml", price: 1599, category: "Hair Care", brand: "Mamaearth", desc: "For damaged hair." },
  { id: 109, name: "Mamaearth Conditioner", size: "300 ml", price: 1599, category: "Hair Care", brand: "Mamaearth", desc: "Conditioner." },
  { id: 114, name: "Sesderma Glycolic Shampoo", size: "200 ml", price: 5299, category: "Hair Care", brand: "Sesderma", desc: "Premium shampoo." },
  { id: 120, name: "Mamaearth Keratin", size: "200 ml", price: 1499, category: "Hair Care", brand: "Mamaearth", desc: "Keratin treatment." },
  { id: 128, name: "Foltene Pharma Promo", size: "200 ml", price: 8999, category: "Hair Care", brand: "Foltene", desc: "Hair loss treatment." },
  { id: 141, name: "Wow Apple Cider Shampoo", size: "300 ml", price: 499, category: "Hair Care", brand: "Wow", desc: "ACV Shampoo." },
  { id: 142, name: "Wow Apple Cider Shampoo", size: "200 ml", price: 299, category: "Hair Care", brand: "Wow", desc: "ACV Shampoo." },
  { id: 143, name: "Wow Hair Loss Therapy", size: "200 ml", price: 299, category: "Hair Care", brand: "Wow", desc: "Therapy shampoo." },
  { id: 144, name: "Wow Argan Oil Shampoo", size: "200 ml", price: 299, category: "Hair Care", brand: "Wow", desc: "Argan oil." },
  { id: 145, name: "Wow Red Onion Shampoo", size: "200 ml", price: 299, category: "Hair Care", brand: "Wow", desc: "Onion shampoo." },
  { id: 148, name: "Wow Coconut Milk Shampoo", size: "100 ml", price: 130, category: "Hair Care", brand: "Wow", desc: "Coconut milk shampoo." },
  { id: 153, name: "Wow Conditioner", size: "200 ml", price: 275, category: "Hair Care", brand: "Wow", desc: "Conditioner." },

  // Skin Care
  { id: 4, name: "Vatika Naturals Body Lotion", size: "200 ML", price: 500, category: "Skin Care", brand: "Vatika", desc: "Moisturizing lotion." },
  { id: 12, name: "Vaseline Intensive Care", size: "400 ML", price: 565, category: "Skin Care", brand: "Vaseline", desc: "Light lotion." },
  { id: 13, name: "Parachute Body Lotion", size: "250 ML", price: 225, category: "Skin Care", brand: "Parachute", desc: "Coconut lotion." },
  { id: 14, name: "Parachute Body Lotion", size: "400 ML", price: 335, category: "Skin Care", brand: "Parachute", desc: "Deep moisturizer." },
  { id: 17, name: "Ponds Skin Institute", size: "180 ML", price: 218, category: "Skin Care", brand: "Ponds", desc: "Face wash." },
  { id: 20, name: "St. Ives Hydrating Face Wash", size: "50 g", price: 110, category: "Skin Care", brand: "St. Ives", desc: "Hydrating wash." },
  { id: 21, name: "Charmis Radiance Face Wash", size: "50 ML", price: 199, category: "Skin Care", brand: "Charmis", desc: "Vitamin C wash." },
  { id: 22, name: "Boro Plus Aloe Vera Gel", size: "60 ML", price: 55, category: "Skin Care", brand: "Boro Plus", desc: "Aloe vera gel." },
  { id: 23, name: "Vatika Sandal Wood Wash", size: "150 ML", price: 170, category: "Skin Care", brand: "Vatika", desc: "Sandalwood face wash." },
  { id: 24, name: "Medimix Ayurvedic Wash", size: "150 ML", price: 175, category: "Skin Care", brand: "Medimix", desc: "Anti-pimple wash." },
  { id: 29, name: "Plum Green Tea Toner", size: "50 ML", price: 149, category: "Skin Care", brand: "Plum", desc: "Alcohol-free toner." },
  { id: 30, name: "Plum Hello Aloe Gel", size: "25 g", price: 99, category: "Skin Care", brand: "Plum", desc: "Aloe vera gel." },
  { id: 33, name: "Dot & Key Watermelon", size: "15 ML", price: 99, category: "Skin Care", brand: "Dot & Key", desc: "Skin care." },
  { id: 34, name: "Dot & Key Cica Calming", size: "15 ML", price: 99, category: "Skin Care", brand: "Dot & Key", desc: "Calming gel." },
  { id: 36, name: "Olay Total Effects", size: "20 g", price: 375, category: "Skin Care", brand: "Olay", desc: "Anti-aging cream." },
  { id: 40, name: "Nivea Fresh Natural", size: "50 ML", price: 185, category: "Skin Care", brand: "Nivea", desc: "Deodorant." },
  { id: 47, name: "ZM Vitamin-C Lotion", size: "100 ML", price: 120, category: "Skin Care", brand: "ZM", desc: "Body lotion." },
  { id: 52, name: "Medimix Face Scrub", size: "140 ML", price: 130, category: "Skin Care", brand: "Medimix", desc: "Face scrub." },
  { id: 56, name: "Joy Nourishing Lotion", size: "40 ML", price: 45, category: "Skin Care", brand: "Joy", desc: "Body lotion." },
  { id: 57, name: "Nivea Gel Body Lotion", size: "75 ML", price: 149, category: "Skin Care", brand: "Nivea", desc: "Gel lotion." },
  { id: 60, name: "Plum Sleeping Mask", size: "100 g", price: 990, category: "Skin Care", brand: "Plum", desc: "Night mask." },
  { id: 63, name: "Organic Harvest Soap", size: "Pack", price: 349, category: "Skin Care", brand: "Organic Harvest", desc: "Organic soap." },
  { id: 65, name: "MyGlamm Wipe Out Soap", size: "75 g", price: 60, category: "Skin Care", brand: "MyGlamm", desc: "Soap." },
  { id: 69, name: "Sugar Pop Sunscreen", size: "50 g", price: 349, category: "Skin Care", brand: "Sugar", desc: "Sunscreen." },
  { id: 97, name: "Tetmosol Icy Cool", size: "75 g", price: 75, category: "Skin Care", brand: "Tetmosol", desc: "Medicated soap." },
  { id: 99, name: "Khadi Vitamin C Mask", size: "1 pc", price: 149, category: "Skin Care", brand: "Khadi", desc: "Sheet mask." },
  { id: 101, name: "Khadi Vitamin C Wash", size: "100 ml", price: 249, category: "Skin Care", brand: "Khadi", desc: "Face wash." },
  { id: 102, name: "Khadi Charcoal Wash", size: "100 ml", price: 299, category: "Skin Care", brand: "Khadi", desc: "Charcoal wash." },
  { id: 110, name: "Winyfred Acne Wash", size: "250 ml", price: 1099, category: "Skin Care", brand: "Winyfred", desc: "Acne wash." },
  { id: 111, name: "ZM Pearly Glow", size: "25 ml", price: 130, category: "Skin Care", brand: "ZM", desc: "Glow cream." },
  { id: 112, name: "Sweet Bliss Face Scrub", size: "75 g", price: 280, category: "Skin Care", brand: "Sweet Bliss", desc: "Scrub." },
  { id: 115, name: "Sesderma Body Milk", size: "250 ml", price: 7999, category: "Skin Care", brand: "Sesderma", desc: "Body milk." },
  { id: 116, name: "DermaVive Hydra Cleanser", size: "120 ml", price: 799, category: "Skin Care", brand: "DermaVive", desc: "Cleanser." },
  { id: 117, name: "Garnier Vitamin C Serum", size: "45 g", price: 189, category: "Skin Care", brand: "Garnier", desc: "Serum gel." },
  { id: 118, name: "Mamaearth Pigmentation Gel", size: "200 ml", price: 1499, category: "Skin Care", brand: "Mamaearth", desc: "Gel." },
  { id: 121, name: "Mamaearth Rice Water", size: "200 ml", price: 1499, category: "Skin Care", brand: "Mamaearth", desc: "Face wash/toner." },
  { id: 122, name: "Mamaearth Sleeping Mask", size: "200 ml", price: 1499, category: "Skin Care", brand: "Mamaearth", desc: "Sleeping mask." },
  { id: 130, name: "Wow Facial Kit", size: "Kit", price: 325, category: "Skin Care", brand: "Wow", desc: "Facial kit." },
  { id: 131, name: "Wow Ubtan Wash", size: "50 ml", price: 125, category: "Skin Care", brand: "Wow", desc: "Ubtan face wash." },
  { id: 132, name: "Wow Ubtan Wash (L)", size: "100 ml", price: 299, category: "Skin Care", brand: "Wow", desc: "Ubtan face wash." },
  { id: 133, name: "Wow Vitamin-C Wash", size: "50 ml", price: 125, category: "Skin Care", brand: "Wow", desc: "Vitamin C wash." },
  { id: 134, name: "Wow Sunscreen", size: "80 ml", price: 299, category: "Skin Care", brand: "Wow", desc: "Sunscreen." },
  { id: 138, name: "Wow Ubtan Foaming", size: "150 ml", price: 499, category: "Skin Care", brand: "Wow", desc: "Foaming wash." },
  { id: 140, name: "Wow ACV Foaming", size: "150 ml", price: 499, category: "Skin Care", brand: "Wow", desc: "ACV wash." },
  { id: 150, name: "Wow Body Lotion", size: "200 ml", price: 299, category: "Skin Care", brand: "Wow", desc: "Body lotion." },
  { id: 151, name: "Wow Shea Butter", size: "200 ml", price: 499, category: "Skin Care", brand: "Wow", desc: "Shea butter lotion." },
  { id: 154, name: "Wow Plush Lotion", size: "300 ml", price: 400, category: "Skin Care", brand: "Wow", desc: "Plush lotion." },

  // Makeup
  { id: 32, name: "Faces Canada Nail Remover", size: "30 ML", price: 99, category: "Makeup", brand: "Faces Canada", desc: "Nail remover." },
  { id: 37, name: "Olay BB Cream", size: "50 g", price: 849, category: "Makeup", brand: "Olay", desc: "BB Cream." },
  { id: 66, name: "MyGlamm FF Cream", size: "10.5 g", price: 1450, category: "Makeup", brand: "MyGlamm", desc: "Foundation." },
  { id: 67, name: "MyGlamm Nail Duo", size: "2x5ml", price: 295, category: "Makeup", brand: "MyGlamm", desc: "Nail polish." },
  { id: 68, name: "Plum Nail Enamel", size: "11 ml", price: 195, category: "Makeup", brand: "Plum", desc: "Nail polish." },
  { id: 70, name: "Sugar Play Lipstick", size: "4.5 ml", price: 499, category: "Makeup", brand: "Sugar", desc: "Lipstick." },
  { id: 71, name: "Sugar Play Lip Oil", size: "4.4 ml", price: 599, category: "Makeup", brand: "Sugar", desc: "Lip oil." },
  { id: 72, name: "Sugar Pop Matte Lip", size: "1.6 ml", price: 249, category: "Makeup", brand: "Sugar", desc: "Matte lip." },
  { id: 74, name: "Sugar Pop Lip Crayon", size: "4 g", price: 499, category: "Makeup", brand: "Sugar", desc: "Lip crayon." },
  { id: 75, name: "Sugar Pop Nail Lacquer", size: "10 ML", price: 129, category: "Makeup", brand: "Sugar", desc: "Nail polish." },
  { id: 76, name: "Faces Canada Foundation", size: "35 ml", price: 449, category: "Makeup", brand: "Faces Canada", desc: "Foundation." },
  { id: 77, name: "Sugar Gel Eyeliner", size: "2.3 g", price: 649, category: "Makeup", brand: "Sugar", desc: "Eyeliner." },
  { id: 78, name: "Sugar Liquid Lipstick", size: "4.5 ml", price: 499, category: "Makeup", brand: "Sugar", desc: "Liquid lipstick." },
  { id: 79, name: "Plum Matte Liner", size: "3.5 ml", price: 345, category: "Makeup", brand: "Plum", desc: "Eyeliner." },
  { id: 80, name: "TAC Liquid Lipstick", size: "Standard", price: 599, category: "Makeup", brand: "TAC", desc: "Liquid lipstick." },
  { id: 81, name: "Sugar Matte Satin", size: "2.2 g", price: 1049, category: "Makeup", brand: "Sugar", desc: "Lipstick." },
  { id: 82, name: "Sugar Matte Liquid", size: "7 ml", price: 1249, category: "Makeup", brand: "Sugar", desc: "Lipstick." },
  { id: 83, name: "Sugar Translucent Powder", size: "7 g", price: 649, category: "Makeup", brand: "Sugar", desc: "Powder." },
  { id: 84, name: "Sugar Banana Compact", size: "6 g", price: 649, category: "Makeup", brand: "Sugar", desc: "Compact." },
  { id: 85, name: "Sugar Dream Cover", size: "6g", price: 549, category: "Makeup", brand: "Sugar", desc: "Compact." },
  { id: 86, name: "Sugar Face Palette", size: "20.3 g", price: 1099, category: "Makeup", brand: "Sugar", desc: "Palette." },
  { id: 87, name: "Sugar Mini Brush", size: "4 g", price: 375, category: "Makeup", brand: "Sugar", desc: "Brush." },
  { id: 89, name: "Sugar Intense Kajal", size: "0.25 g", price: 249, category: "Makeup", brand: "Sugar", desc: "Kajal." },
  { id: 90, name: "Sugar Brow Styler", size: "5 g", price: 699, category: "Makeup", brand: "Sugar", desc: "Eyebrow pencil." },
  { id: 91, name: "Sugar Pop Intense Kohl", size: "1.2 g", price: 329, category: "Makeup", brand: "Sugar", desc: "Kohl." },
  { id: 92, name: "Sugar Tipsy Lips", size: "4.5 g", price: 199, category: "Makeup", brand: "Sugar", desc: "Lip balm." },

  // Men & Personal
  { id: 18, name: "Bombae Hair Removal", size: "30 g", price: 85, category: "Personal Care", brand: "Bombae", desc: "Hair remover." },
  { id: 19, name: "Eve Care Intimate", size: "90 ML", price: 165, category: "Personal Care", brand: "Eve Care", desc: "Intimate wash." },
  { id: 39, name: "Nivea Men Cool Kick", size: "50 ML", price: 165, category: "Men's Grooming", brand: "Nivea", desc: "Lotion." },
  { id: 41, name: "Park Avenue Cool Blue", size: "50 ML", price: 140, category: "Men's Grooming", brand: "Park Avenue", desc: "After shave." },
  { id: 42, name: "Nivea Men Deodorizer", size: "100 ML", price: 225, category: "Men's Grooming", brand: "Nivea", desc: "Deodorant." },
  { id: 43, name: "Nivea Men Deep Impact", size: "200 ML", price: 225, category: "Men's Grooming", brand: "Nivea", desc: "Shaving lotion." },
  { id: 45, name: "Graphite Perfume", size: "150 ML", price: 199, category: "Fragrance", brand: "Generic", desc: "Perfume." },
  { id: 46, name: "Colgate MaxFresh", size: "250 ML", price: 165, category: "Personal Care", brand: "Colgate", desc: "Toothpaste." },
  { id: 48, name: "Dr + Rhazes Spray", size: "73 g", price: 200, category: "Personal Care", brand: "Dr Rhazes", desc: "Spray." },
  { id: 50, name: "Fogg Master", size: "120 g", price: 125, category: "Fragrance", brand: "Fogg", desc: "Body spray." },
  { id: 51, name: "Himalaya Pain Balm", size: "10 g", price: 50, category: "Personal Care", brand: "Himalaya", desc: "Balm." },
  { id: 54, name: "Iodex Power Gel", size: "10 g", price: 50, category: "Personal Care", brand: "Iodex", desc: "Pain relief gel." },
  { id: 62, name: "Plix Perfume", size: "100 ML", price: 700, category: "Fragrance", brand: "Plix", desc: "Perfume." },
  { id: 95, name: "The Man Company Wash", size: "250 ml", price: 299, category: "Men's Grooming", brand: "The Man Company", desc: "Body wash." },
  { id: 96, name: "Lifebuoy Wet Wipes", size: "Pack", price: 80, category: "Personal Care", brand: "Lifebuoy", desc: "Wipes." },
  { id: 98, name: "Agnistar", size: "50 g", price: 150, category: "Personal Care", brand: "Agnistar", desc: "Personal care." },
  { id: 123, name: "Epilation Summer", size: "250 ml", price: 1999, category: "Personal Care", brand: "Generic", desc: "Epilation." },
  { id: 124, name: "One 8 Perfume Set", size: "Combo", price: 1850, category: "Fragrance", brand: "One 8", desc: "Gift set." },
  { id: 125, name: "Godrej Aer Spray", size: "Standard", price: 169, category: "Home", brand: "Godrej", desc: "Room spray." },
  { id: 126, name: "Envy Natural Spray", size: "30 ml", price: 175, category: "Fragrance", brand: "Envy", desc: "Perfume." },
  { id: 127, name: "One 8 Perfume", size: "200 ml", price: 399, category: "Fragrance", brand: "One 8", desc: "Perfume." },
  { id: 129, name: "One 8 EDP", size: "100 ml", price: 1495, category: "Fragrance", brand: "One 8", desc: "Perfume." },
  { id: 137, name: "Wow Freedom", size: "Standard", price: 599, category: "Personal Care", brand: "Wow", desc: "Pad." },
  { id: 155, name: "Carmesi Disposal Bags", size: "Pack", price: 200, category: "Personal Care", brand: "Carmesi", desc: "Bags." },
];

export const INITIAL_CATALOG: Product[] = RAW_DATA.map((p) => ({
  ...p,
  mrp: Math.floor(p.price * 1.4),
  off: Math.floor(((p.price * 1.4 - p.price) / (p.price * 1.4)) * 100),
  image: null,
}));
